twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@TetranzSelect2Entity/Form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
        form_themes:
            - '@TetranzSelect2Entity/Form/fields.html.twig'
